AllCops:
  Exclude:
    - 'spec/files/measures/**/*'
    - 'spec/files/measures_second_path/**/*'
    - 'spec/files/worker_init/*'

inherit_from:
  - https://raw.githubusercontent.com/NREL/OpenStudio-resources/add-styles-linters/styles/rubocop.yml
