AllCops:
  Exclude:
    - 'spec/files/measures/**/*'
    - 'spec/files/measures_second_path/**/*'
    - 'spec/files/worker_init/*'

inherit_from:
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop_v3.yml
