AllCops:
  Exclude:
    - 'spec/files/measures/**/*'
    - 'spec/files/measures_second_path/**/*'
    - 'spec/files/worker_init/*'

# ==================== Linters ====================
Lint/AmbiguousOperator:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/UnreachableCode:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true

Lint/UnusedBlockArgument:
  Description: 'Checks for unused block arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars'
  Enabled: false

Lint/UnusedMethodArgument:
  Description: 'Checks for unused method arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars'
  Enabled: false

Lint/UselessAssignment:
  Description: 'Checks for useless assignment to a local variable.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars'
  Enabled: false

# ==================== Performance ========================

Performance/Casecmp:
  Enabled: false

# ==================== Styles / Metrics====================

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 350

Metrics/ParameterLists:
  Max: 8

# ==================== Disabled on Purpose ====================

# Allow indented case statements
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles, SingleLineConditionsOnly.
# SupportedStyles: assign_to_condition, assign_inside_condition
Style/ConditionalAssignment:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

# Offense count: 1
Style/EachWithObject:
  Enabled: false

# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: true

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: symmetrical, new_line, same_line
Style/MultilineMethodCallBraceLayout:
  Enabled: false

# Do NOT enable.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/Next:
  Enabled: false

Style/NumericLiterals:
  Description: 'Add underscores to large numeric literals to improve readability.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscores-in-numerics'
  Enabled: false

# Configuration parameters: AutoCorrect, EnforcedStyle, SupportedStyles.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Enabled: false

# More Changes per DLM -- pulled from https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
Style/RedundantReturn:
  Description: 'Do not use return where it is not required.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-explicit-return'
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

# Do NOT enable this because it appears $? is different than $CHILD_STATUS.
Style/SpecialGlobalVars:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

